### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by jwarner112** [seek-oss/aws-sm-buildkite-plugin#13]
Hey there,

I'd like to be able to make decent use of this plugin but my use case doesn't fit in the four or five examples provided in `README.md`.

I'm becoming familiar with Buildkite as a new tool for my organization or I'd probably be able to just pore over the source code... In the mean time, where can I find a more complete documentation for this?

Thanks!

**Comment by zsims** [comment]
Hello 😄 

I'm interested in your use-case, what's missing from the plugin? As for documentation, it's just:

 - [The README](https://github.com/seek-oss/aws-sm-buildkite-plugin/blob/master/README.md)
 - [The Buildkite Plugin Docs](https://buildkite.com/docs/pipelines/plugins)
 - [The AWS SecretsManager Docs](https://docs.aws.amazon.com/secretsmanager/index.html) 
 - [The AWS CLI SecretsManager Docs](https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/index.html)

**Comment by jwarner112** [comment]
Hey there,

Sorry about the slow reply. I had forgotten about this. I neglected to mention that I'm getting familiar with AWS at the same time and misunderstood that I cannot make `SecretBinary` secrets from the web UI, so I assumed this plugin was the problem.

I can only maybe suggest adding an example that shows retrieving a SecretBinary with some kind of note that you can only make those from the CLI? that's not really your problem but may save you headache if I'm not alone in filing an issue like this

Thanks anyhow. Cheers!

**Comment by zsims** [comment]
Sure, will do. Makes sense :)

Thanks for the info, and trying the plugin
