### ISSUE TITLE
env-buildkite-plugin not found

### ISSUE THREAD

**Issue by linchen-myob** [seek-oss/aws-sm-buildkite-plugin#14]
this plugin will clone https://github.com/buildkite-plugins/env-buildkite-plugin, but it's not exists any longer

**Comment by zsims** [comment]
It shouldn't, it doesn't depend on any other plugins.

This can happen if your YAML indenting or `:` have been left off. How are you referencing this plugin?

**Comment by zsims** [comment]
Please re-open if it turns out not to be YAML indenting
